### ISSUE TITLE
example

### ISSUE THREAD

**Issue by kamil7732** [Appsolutly/node-regon#1]
Could you do a bit more structured example?
The present example has lots of commented out code.
The uncommented code doesn't work out of the box.
Even after correcting it I can't get the fullreport from gus.

**Comment by adamkac** [comment]
Hi, sorry for that, it shouldn't be commited.
For some days we have some problems with GUS API sandbox,
so if You want to test it, you will need to have Your own production key.

I have added some comments in example.js file, so maybe now it is more clear...

Just fill keys With your data, fill anti-captcha.com api if you want and run
node ./examples/example.js

If you want to see what is going on behind run:
DEBUG=* node ./examples/example.js

Cheers!
