### ISSUE TITLE
Upgrade to BIR1.1?

### ISSUE THREAD

**Issue by Rigel772** [Appsolutly/node-regon#12]
Is there a chance to upgrade to  BIR1.1 version?
DaneSzukaj (BIR1) -> DaneSzukajPodmioty (BIR1.1)
The search is not returning full address...
![image](https://user-images.githubusercontent.com/1696243/212461494-db565617-6b45-440b-9dca-b7367b2fd42f.png)

**Comment by adamkac** [comment]
Hi, added BIR 1.1.
Configurable with birVersion option
