### ISSUE TITLE
problem z raportem dla DG

### ISSUE THREAD

**Issue by mrdannael** [Appsolutly/node-regon#2]
Pobieranie danych z wykorzystaniem NIP'ów należących do działaności gosporaczych nie działa. Otrzymuję pusty raport. 
Nie ma takiego problemu, jeżeli wykorzystujemy NIP'y spółek.

**Comment by adamkac** [comment]
W ostatniej aktualizacji ten problem powinien być rozwiązany. Przepraszam za długi czas oczekiwania, nie rozwijałem tego projektu w minionym roku.
