### ISSUE TITLE
Request body gets escaped unnecessarily

### ISSUE THREAD

**Issue by iKonrad** [Appsolutly/node-regon#5]
I'm trying to integrate this library with my app, but it doesn't seem to work out of the box.

I'm creating a client and passing a key over to the constructor. That should log me in automatically, however, I'm getting a Internal Error issue back from the API.

The reason for this is that the request body gets escaped which apparently is something that the REGON API doesn't like.

Here's the final request:
```
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://CIS/BIR/PUBL/2014/07" xmlns:i0="http://CIS/BIR/PUBL/2014/07" xmlns:q1="http://CIS/BIR/2014/07" xmlns:q2="http://CIS/BIR/2014/07" xmlns:q3="http://CIS/BIR/2014/07" xmlns:q4="http://CIS/BIR/2014/07" xmlns:q5="http://CIS/BIR/2014/07" xmlns:q6="http://CIS/BIR/2014/07" xmlns:q7="http://CIS/BIR/2014/07" xmlns:q8="http://CIS/BIR/2014/07" xmlns:ns="http://CIS/BIR/2014/07"><soap:Header xmlns:wsa="http://www.w3.org/2005/08/addressing">
<wsa:To>https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc</wsa:To>
<wsa:Action>http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj</wsa:Action></soap:Header><soap:Body>
<IUslugaBIRzewnPubl_Zaloguj_InputMessage>&lt;tns:Zaloguj&gt;&lt;tns:pKluczUzytkownika&gt;MYAPIKEY&lt;/tns:pKluczUzytkownika&gt;&lt;/tns:Zaloguj&gt;</IUslugaBIRzewnPubl_Zaloguj_InputMessage>
</soap:Body>
</soap:Envelope>
```

Is there a reason behind this? I've tried without the escaping and it worked so I'm 100% sure it's this escaping that's breaking things.

**Comment by iKonrad** [comment]
My bad, it seems that it's not the encoding, but the `<
IUslugaBIRzewnPubl_Zaloguj_InputMessage>` tag that is not required but wraps the login body.

**Comment by iKonrad** [comment]
@adamkac I know it's been a while since the last time you looked at this project, but maybe you have any idea on how to get rid of the `IUslugaBIRzewnPubl_Zaloguj_InputMessage`? I'm afraid this is where my knowledge about SOAP APIs end and I'd really want to get this sorted. 

Thanks in advance

**Comment by adamkac** [comment]
Hi, i have updated some wsdl settings and i also changed way of passing params to SOAP methods, and it looks like it is ok now. Please let me know if this last release solved Your problems.
