### ISSUE TITLE
Problem with loading street number in JDG

### ISSUE THREAD

**Issue by awedzikowski** [Appsolutly/node-regon#9]
Przy próbie zaciągnięcia danych po numerze NIP, w przypadku jednoosobowych działalności gospodarczych, nie zaciąga się numer ulicy. https://github.com/Appsolutly/node-regon/blob/master/examples/example.js#L51 wg tego linka używamy full report, tam powinny być pola jak fullReport.fiz_adSiedzNumerNieruchomosci oraz fullReport.fiz_adSiedzNumerLokalu, ale dla dowolnej JDG tego nie ma.

**Comment by tosowiecki** [comment]
Podobny problem. W przypadku JDG fullReport getFullReport  zwraca { error: null, response: undefined }

**Comment by adamkac** [comment]
Przepraszam nie zaglądałem tu długo, leci poprawka na pobieranie pełnego raportu w JDG.
CO do braku numeru ulicy - tak dzieje się w sandbox, @awedzikowski potwierdź prosze, czy problem występował w sandbox.
